services:
  era-test-node-1:
    build:
      context: ./era-test-node
      dockerfile: Dockerfile
      args:
        CHAIN_ID: 500
        PORT: 8012
    ports:
      - "8012:8012"
    networks:
      - era-network

  era-test-node-2:
    build:
      context: ./era-test-node
      dockerfile: Dockerfile
      args:
        CHAIN_ID: 501
        PORT: 8013
    ports:
      - "8013:8013"
    networks:
      - era-network

  slingshot-init:
    build:
      context: ./slingshot
      dockerfile: Dockerfile
      args:
        PRIV_KEY: "0x3d3cbc973389cb26f657686445bcc75662b415b656078503592ac8c1abb8810e"
        CHAIN_1_RPC: "http://host.docker.internal:8012/"
        CHAIN_2_RPC: "http://host.docker.internal:8013/"
    networks:
      - era-network
    depends_on:
      - era-test-node-1
      - era-test-node-2

  slingshot:
    build:
      context: ./slingshot/cli
      dockerfile: Dockerfile
      args:
        PRIV_KEY: "0x3d3cbc973389cb26f657686445bcc75662b415b656078503592ac8c1abb8810e"
        INTEROP_ADDR: "0x7122bb051DE72eAD9CE1F6374BEaCBc38E81fdb1"
        CHAIN_1_RPC: "http://host.docker.internal:8012/"
        CHAIN_2_RPC: "http://host.docker.internal:8013/"
    networks:
      - era-network
    depends_on:
      slingshot-init:
        condition: service_completed_successfully

networks:
  era-network:
    driver: bridge
