[profile.default]
src = "src"
out = "out"
libs = ["lib", "slingshot/src"]
solc_version = '0.8.20'
evm_version = "cancun"  

remappings = [
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.default.zksync] 
enable_eravm_extensions = true
zksolc = "1.5.3"

[rpc_endpoints]
chain_a = "http://127.0.0.1:8012"
chain_b = "http://127.0.0.1:8013"
